pipeline{
    agent any
    stages{
        stage("Build"){
            agent{
                docker {
                    image 'node:22.5.1'
                    reuseNode
                }
            } 
            steps{
               sh '''                
                node --version
                npm --version
                ls -la
                npm ci
                npm run build
                ls -la
               '''
            }   
        }
    }
}