pipeline{
    agent any

    /*
    *netlifysite
    *netlifytoken
    *
    */
    environment{
        NETLIFY_SITE_ID = 'a66550cd-078e-4038-924b-b5c4b0e8914f'
        NETLIFY_AUTH_TOKEN = credentials('netlify-token')
    }

    stages{
        // THE ADD BUILD STEP STARTED 
        stage("Build"){
            agent{
                docker {
                    image 'node:22.5.1'
                    reuseNode true
                }
            } 
            steps{
               sh '''                
                node --version
                npm --version
                #ls -la
                npm ci
                npm run build
                #ls -la
               '''
            }   
        }

        stage('deployment'){
            agent{
                docker {
                    image 'node:22.5.1'
                    reuseNode true
                }
            }
            steps{
                sh '''
                    npm install netlify-cli
                    node_modules/.bin/netlify --version
                    node_modules/.bin/netlify status
                    node_modules/.bin/netlify deploy --dir=dist --prod
                '''
            }
        }
    }
}