pipeline{
    agent any
   
    environment{
        //netlify side Id.
        // netlify auth token saved in jenkin credentials
        NETLIFY_SITE_ID = 'a66550cd-078e-4038-924b-b5c4b0e8914f'
        NETLIFY_AUTH_TOKEN = credentials('netlify-token')
    }

    stages{
        // THE ADD BUILD STEP STARTED 
        stage("Git Checkout"){
            steps{
                git checkout: 'main', url:'https://github.com/webtech-coding/geo-cities.git'
            }
        }

        stage("NPM Build"){
            agent{
                docker {
                    image 'node:22.5.1'
                    reuseNode true
                }
            }
            environment{
                VITE_GEO_HOST = 'wft-geo-db.p.rapidapi.com'
                VITE_GEO_HOST_KEY = credentials('geo-host-key')
            }
            steps{
               sh '''
                set VITE_GEO_HOST =${VITE_GEO_HOST}
                set VITE_GEO_HOST_KEY=${VITE_GEO_HOST_KEY}       
                node --version
                npm --version
                #ls -la
                npm ci
                npm run build
                #ls -la
               '''
            }   
        }

        stage('Prod Deployment'){
            agent{
                docker {
                    image 'node:22.5.1'
                    reuseNode true
                }
            }
            steps{
                sh '''
                    npm install netlify-cli
                    node_modules/.bin/netlify --version
                    node_modules/.bin/netlify status
                    node_modules/.bin/netlify deploy --dir=dist --prod
                '''
            }
        }
    }
}